yarn add expo
레포지토리 이동 후 npx expo start 후 아래의 에러 발생

ConfigError: Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.